// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtY7sKpxTFYoWNpitAkNkBJ_wKSI2TyFU',
    appId: '1:563144803073:android:2d5dcfead8256489729100',
    messagingSenderId: '563144803073',
    projectId: 'mynotes-matt-tif',
    storageBucket: 'mynotes-matt-tif.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRLzvqB21mg0w_TkiFr5PB-iU5pFbNqu8',
    appId: '1:563144803073:ios:e7a75f757248ff26729100',
    messagingSenderId: '563144803073',
    projectId: 'mynotes-matt-tif',
    storageBucket: 'mynotes-matt-tif.appspot.com',
    iosClientId: '563144803073-q8nii7k30shvia2u04srmdp2feu2k0aq.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
